# Generated by Django 5.2.1 on 2026-01-21 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_remove_cart_branch_remove_invoice_branch_and_more'),
        ('users', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('sale_create', 'Sale Created'), ('sale_complete', 'Sale Completed'), ('sale_void', 'Sale Voided'), ('sale_edit', 'Sale Edited'), ('stock_deduct', 'Stock Deducted'), ('stock_restore', 'Stock Restored'), ('payment_create', 'Payment Created'), ('payment_void', 'Payment Voided'), ('cart_hold', 'Cart Held'), ('cart_void', 'Cart Voided'), ('admin_action', 'Admin Action')], max_length=20)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['operation', 'timestamp'], name='sales_audit_operati_717c42_idx'), models.Index(fields=['user', 'timestamp'], name='sales_audit_user_id_802fa7_idx'), models.Index(fields=['entity_type', 'entity_id'], name='sales_audit_entity__0c141a_idx')],
            },
        ),
    ]
