# Generated by Django 5.2.1 on 2026-02-07 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_return_new_items_total_return_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='return_code_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='return_code_used',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ReturnCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('original_receipt_number', models.CharField(max_length=50)),
                ('return_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_codes', to='sales.return')),
                ('used_in_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_return_codes', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'status'], name='sales_retur_code_eeba68_idx'), models.Index(fields=['status', 'created_at'], name='sales_retur_status_c231de_idx')],
            },
        ),
    ]
