# Generated by Django 5.2.1 on 2026-02-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_shift_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='net_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shift',
            name='return_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shift',
            name='total_returns',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
