# Generated by Django 5.2.1 on 2026-02-06 13:44

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0016_return_new_items_total_return_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETimsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Primary POS', max_length=100)),
                ('tin', models.CharField(help_text='Tax Identification Number', max_length=20)),
                ('branch_id', models.CharField(help_text='Branch ID (MRC)', max_length=10)),
                ('device_serial', models.CharField(help_text='Device Serial Number (S/N)', max_length=50)),
                ('api_key', models.CharField(help_text='eTIMS API Key', max_length=256)),
                ('api_secret', models.CharField(help_text='eTIMS API Secret', max_length=256)),
                ('is_sandbox', models.BooleanField(default=True, help_text='Use sandbox/test environment')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'eTIMS Configuration',
                'verbose_name_plural': 'eTIMS Configurations',
            },
        ),
        migrations.CreateModel(
            name='OfflineTransactionQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('return', 'Return'), ('void', 'Void')], max_length=20)),
                ('reference_id', models.CharField(help_text='Reference to original record', max_length=100)),
                ('payload', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Offline Transaction Queue',
                'verbose_name_plural': 'Offline Transaction Queues',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FiscalReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('kra_serial', models.CharField(blank=True, help_text='KRA assigned serial number', max_length=50, null=True)),
                ('receipt_datetime', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('customer_tin', models.CharField(blank=True, help_text='Customer TIN', max_length=20, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('return', 'Return/Refund'), ('void', 'Void')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to KRA'), ('signed', 'KRA Signed'), ('failed', 'Failed'), ('voided', 'Voided')], default='pending', max_length=20)),
                ('raw_response', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('return_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_receipts', to='sales.return')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_receipts', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Fiscal Receipt',
                'verbose_name_plural': 'Fiscal Receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ETimsApiLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=500)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10)),
                ('request_payload', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('response_payload', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiscal_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etims.fiscalreceipt')),
            ],
            options={
                'verbose_name': 'eTIMS API Log',
                'verbose_name_plural': 'eTIMS API Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FiscalReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(help_text='Product Code (SKU or Barcode)', max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('hs_code', models.CharField(blank=True, help_text='HS Code for customs', max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16.0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='etims.fiscalreceipt')),
            ],
            options={
                'verbose_name': 'Fiscal Receipt Item',
                'verbose_name_plural': 'Fiscal Receipt Items',
            },
        ),
    ]
