# Generated by Django 5.2.1 on 2026-02-13 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_sale_return_code_amount_sale_return_code_used_and_more'),
        ('shifts', '0005_shift_net_sales_shift_return_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='shifts.shift'),
        ),
    ]
