# Generated by Django 5.2.1 on 2026-02-13 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_return_shift_receipt_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(max_length=10, unique=True)),
                ('last_number', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Receipt Counter',
                'verbose_name_plural': 'Receipt Counters',
            },
        ),
        migrations.RemoveField(
            model_name='returncode',
            name='return_record',
        ),
        migrations.RemoveField(
            model_name='returncode',
            name='used_in_sale',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='return_record',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='sale_item',
        ),
        migrations.RemoveField(
            model_name='return',
            name='new_items_total',
        ),
        migrations.RemoveField(
            model_name='return',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='return',
            name='price_difference',
        ),
        migrations.AlterField(
            model_name='return',
            name='total_refund_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='ExchangeItem',
        ),
        migrations.DeleteModel(
            name='ReturnCode',
        ),
        migrations.DeleteModel(
            name='ReturnItem',
        ),
    ]
