# Generated by Django 5.2.1 on 2026-02-13 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_add_return_code_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitem',
            name='reason',
            field=models.TextField(),
        ),
    ]
