# Generated by Django 5.2.1 on 2026-02-13 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_return_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returncode',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='returncode',
            name='return_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_codes', to='sales.return'),
        ),
        migrations.AlterField(
            model_name='returncode',
            name='used_in_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_return_codes', to='sales.sale'),
        ),
    ]
