# Generated by Django 5.2.1 on 2026-02-17 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_producthistory'),
        ('sales', '0023_saleitem_returned_quantity'),
    ]

    operations = []
